[project]
name = "fastapi-base-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.4",
    "pydantic-settings>=2.6.1",
    "ruff>=0.7.3",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.0",
]
